2022-09-25 23:33:57,183 - fishTrade_main20220913.py[line:583] - INFO: 
                  ET网格智能交易系统3.0             
*************************版权声明***************************             
********************All Rights Reserved*********************             
软件开发：海易，需求订制联系微信：yyy99966             
优惠版：有效期30天，每分享一个好友，延长30天，10个延长一年

2022-09-25 23:33:57,184 - fishTrade_main20220913.py[line:147] - INFO: 初始参数设置:symbol=eth_usdt highPrice=1700.0 lowPrice=1200.0  step_num=70.0
2022-09-25 23:33:58,951 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:33:58,953 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:34:00,967 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:34:04,111 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:34:04,111 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:34:06,112 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:34:06,828 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 169, in strategy
    huobi_market.market_detail(self.quote_cur, self.base_cur)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 399, in market_detail
    r = requests.request('GET', acfg.gateApi + prefix + url + "?" + query_param, headers=headers)
  File "D:\Python\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Python\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\Python\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\Python\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\Python\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "D:\Python\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "D:\Python\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "D:\Python\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\Python\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "D:\Python\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "D:\Python\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

2022-09-25 23:34:08,842 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:34:10,571 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:34:10,572 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:34:12,579 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:34:15,304 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:34:15,304 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:34:17,307 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:34:19,044 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:34:19,044 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:34:21,058 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:34:23,828 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:34:23,829 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:34:25,836 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:34:27,772 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:34:27,773 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:34:29,786 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:34:31,398 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:34:31,398 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:34:33,407 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:34:35,156 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:34:35,156 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:34:37,161 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:34:39,532 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:34:39,533 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:34:41,542 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:34:43,504 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:34:43,505 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:34:45,517 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:34:47,709 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:34:47,709 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:34:49,715 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:34:51,409 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:34:51,409 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:34:53,412 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:34:55,258 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:34:55,258 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:34:57,263 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:34:59,242 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:34:59,243 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:35:01,251 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:35:03,266 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:35:03,266 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:35:05,282 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:35:07,101 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:35:07,101 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:35:09,116 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:35:10,984 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:35:10,984 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:35:12,999 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:35:14,850 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:35:14,850 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:35:16,859 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:35:18,752 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:35:18,753 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:35:20,762 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:35:23,181 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:35:23,181 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:35:25,190 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:35:27,347 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:35:27,348 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:35:29,354 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:35:31,578 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:35:31,578 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:35:33,580 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:35:35,578 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:35:35,578 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:35:37,590 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:35:39,580 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:35:39,581 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:35:41,591 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:35:44,947 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:35:44,947 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:35:46,949 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:35:49,090 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:35:49,092 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:35:51,096 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:35:53,170 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:35:53,171 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:35:55,180 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:35:56,918 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:35:56,919 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:35:58,928 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:36:00,841 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:36:00,841 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:36:02,842 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:36:05,387 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:36:05,388 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:36:07,399 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:36:10,406 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:36:10,406 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:36:12,414 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:36:14,780 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:36:14,781 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:36:16,791 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:36:18,710 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:36:18,711 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:36:20,718 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:36:22,986 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:36:22,986 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:36:24,995 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:36:27,131 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:36:27,131 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:36:29,141 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:36:31,494 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:36:31,494 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:36:33,500 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:36:35,673 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:36:35,674 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:36:37,681 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:36:39,330 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:36:39,331 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:36:41,333 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:36:43,807 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:36:43,808 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:36:45,823 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:36:48,275 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:36:48,276 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:36:50,279 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:36:52,245 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:36:52,246 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:36:54,255 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:36:56,739 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:36:56,739 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:36:58,744 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:37:01,561 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:37:01,561 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:37:03,574 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:37:05,109 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:37:05,109 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:37:07,116 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:37:09,433 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:37:09,434 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:37:11,442 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:37:14,078 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:37:14,079 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:37:16,094 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:37:18,731 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:37:18,731 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:37:20,735 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:37:22,564 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:37:22,564 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:37:24,569 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:37:26,540 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:37:26,540 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:37:28,547 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:37:30,613 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:37:30,614 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:37:32,616 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:37:34,443 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:37:34,443 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:37:36,459 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:37:38,610 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:37:38,611 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:37:40,619 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:37:42,624 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:37:42,624 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:37:44,638 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:37:47,150 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:37:47,151 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:37:49,155 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:37:51,120 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:37:51,121 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:37:53,124 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:37:56,174 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:37:56,175 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:37:58,182 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:38:00,223 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:38:00,223 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:38:02,225 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:38:05,854 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:38:05,854 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:38:07,860 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:38:09,832 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:38:09,832 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:38:11,841 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:38:13,868 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:38:13,868 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

2022-09-25 23:38:15,876 - fishTrade_main20220913.py[line:637] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-25 23:38:17,831 - fishTrade_main20220913.py[line:372] - INFO: 多单开仓 size:0.1
2022-09-25 23:38:17,832 - fishTrade_main20220913.py[line:299] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 250, in strategy
    res = self.buy_enter(huobi_market, market_buy_size)
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 374, in buy_enter
    order_result = huobi_market.open_long(cur_market_name=self.get_market_name(self.quote_cur, self.base_cur),
TypeError: Market.open_long() got an unexpected keyword argument 'cur_market_name'

